version: '3.7'

services:
  elasticsearch-01:
    image: $ELK_PROJECT_NAME-elasticsearch:$ELK_PROJECT_NAME-$ELK_PROJECT_VERSION
    container_name: $ELK_PROJECT_NAME-elasticsearch-01
    restart: on-failure

    environment:
      # Identify
      - cluster.name=$ELK_PROJECT_NAME-elasticsearch-cluster
      - node.name=$ELK_PROJECT_NAME-es-node-01

      # Elastic Cluster Network Settings
      - network.host=0.0.0.0
      - http.port=9200
      - transport.port=9300

      # Cluster Connection Settings
      - discovery.seed_hosts=$ELK_PROJECT_NAME-elasticsearch-02:9300
      - cluster.initial_master_nodes=$ELK_PROJECT_NAME-es-node-01, $ELK_PROJECT_NAME-es-node-02

      # ElasticSearch Node Configuration
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1536m -Xmx1536m"

      # Snapshot Dump Path
      - path.repo=/usr/share/elasticsearch/snapshot

    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: "3G"

    networks:
      - elastic-net
    ports:
      - 3200:9200

    volumes:
      - elasticsearch-data-01:/usr/share/elasticsearch/data
      - ./elasticsearch/snapshot:/usr/share/elasticsearch/snapshot


  elasticsearch-02:
    image: $ELK_PROJECT_NAME-elasticsearch:$ELK_PROJECT_NAME-$ELK_PROJECT_VERSION
    container_name: $ELK_PROJECT_NAME-elasticsearch-02
    restart: on-failure

    environment:
      # Identify
      - cluster.name=$ELK_PROJECT_NAME-elasticsearch-cluster
      - node.name=$ELK_PROJECT_NAME-es-node-02

      # Elastic Cluster Network Settings
      - network.host=0.0.0.0
      - http.port=9200
      - transport.port=9300

      # Cluster Connection Settings
      - discovery.seed_hosts=$ELK_PROJECT_NAME-elasticsearch-01:9300
      - cluster.initial_master_nodes=$ELK_PROJECT_NAME-es-node-01, $ELK_PROJECT_NAME-es-node-02

      # ElasticSearch Node Configuration
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1536m -Xmx1536m"

      # Snapshot Dump Path
      - path.repo=/usr/share/elasticsearch/snapshot

    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: "3G"

    networks:
      - elastic-net
    ports:
      - 3201:9200

    volumes:
      - elasticsearch-data-02:/usr/share/elasticsearch/data
      - ./elasticsearch/snapshot:/usr/share/elasticsearch/snapshot


  kibana:
    image: $ELK_PROJECT_NAME-kibana:$ELK_PROJECT_NAME-$ELK_PROJECT_VERSION
    container_name: $ELK_PROJECT_NAME-kibana

    environment:
      ELASTICSEARCH_HOSTS: http://$ELK_PROJECT_NAME-elasticsearch-01:9200

    deploy:
      resources:
        limits:
          memory: "1G"

    networks:
      - elastic-net
    ports:
      - 3601:5601

    depends_on:
      # docker service name
      - elasticsearch-01


#  logstash:
#    image: $ELK_PROJECT_NAME-logstash:$ELK_PROJECT_NAME-$ELK_PROJECT_VERSION
#    container_name: $ELK_PROJECT_NAME-logstash
#    restart: on-failure
#
#    environment:
#      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#
#    networks:
#      - elastic-net
#    ports:
#      - 1301:5044
#
#    volumes:
#      - ./settings:/usr/share/logstash/config
#      - ./settings/logstash.yml:/usr/share/logstash/config/logstash.yml
#      - ./settings/my_pipeline.conf:/usr/share/logstash/config/my_pipeline.conf
#
#    depends_on:
#      # docker service name
#      - elasticsearch-01


volumes:
  elasticsearch-data-01:
    driver: local
#    external:
#      name: $ELK_PROJECT_NAME-elasticsearch-data-01
  elasticsearch-data-02:
    driver: local


networks:
  elastic-net:
    driver: bridge
